# Generated by Django 3.1.2 on 2020-10-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='in_collection',
            field=models.BooleanField(default=False),
        ),
    ]
