# Generated by Django 3.1.2 on 2020-10-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20201011_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='subgenres',
        ),
        migrations.AddField(
            model_name='subgenre',
            name='main_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='records.genre'),
        ),
    ]
