# Generated by Django 3.1.2 on 2020-10-13 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20201011_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='first_released',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='wanted',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
